- pom.xml
- src/main/java/org/mae/twg/backend/config/SecurityConfig.java
- src/main/java/org/mae/twg/backend/controllers/ConfigController.java
- src/main/java/org/mae/twg/backend/models/ConfigParam.java
- src/main/java/org/mae/twg/backend/repositories/ConfigRepo.java
- src/main/java/org/mae/twg/backend/services/ConfigService.java
- src/main/resources/application.properties
Добавлен сервис динамического конфига на Redis
> Dinamic config service

- src/main/java/org/mae/twg/backend/controllers/ConfigController.java
- src/main/java/org/mae/twg/backend/services/ConfigService.java
- src/main/java/org/mae/twg/backend/utils/auth/JwtUtils.java
- src/main/java/org/mae/twg/backend/utils/config/ConfigParam.java
- src/main/java/org/mae/twg/backend/utils/config/ConfigRepo.java
- src/main/java/org/mae/twg/backend/utils/config/ConfigService.java
Внедрены динамические параметры длительности действия токенов
> Dynamic token expiration timouts

- src/main/java/org/mae/twg/backend/controllers/TravelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/BaseTravelController.java
- src/main/java/org/mae/twg/backend/services/TravelService.java
- src/main/java/org/mae/twg/backend/services/travel/CountryService.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/PropertyService.java
- src/main/java/org/mae/twg/backend/services/travel/ResortService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Добавлена поддержка пагинации для запросов на все модели
> Add pagination for travel controllers

- src/main/java/org/mae/twg/backend/controllers/ExampleController.java
- src/main/java/org/mae/twg/backend/controllers/admin/ConfigController.java
- src/main/java/org/mae/twg/backend/dto/admin/ConfigDTO.java
- src/main/java/org/mae/twg/backend/services/ConfigEnum.java
- src/main/java/org/mae/twg/backend/services/ConfigService.java
> Config refactor

- src/main/java/org/mae/twg/backend/CurrencyHistory.java
- src/main/java/org/mae/twg/backend/controllers/admin/ConfigController.java
- src/main/java/org/mae/twg/backend/models/Currency.java
- src/main/java/org/mae/twg/backend/repositories/admin/CurrencyHistoryRepo.java
- src/main/java/org/mae/twg/backend/services/ConfigEnum.java
- src/main/java/org/mae/twg/backend/services/ConfigService.java
- src/main/java/org/mae/twg/backend/services/CurrencyService.java
Add logic for currency history
> Currency history

- src/main/java/org/mae/twg/backend/controllers/auth/AuthController.java
- src/main/java/org/mae/twg/backend/controllers/auth/ProfileController.java
- src/main/java/org/mae/twg/backend/dto/auth/UserDTO.java
- src/main/java/org/mae/twg/backend/models/business/AgencyLocal.java
- src/main/java/org/mae/twg/backend/models/travel/localization/HotelLocal.java
- src/main/java/org/mae/twg/backend/models/travel/localization/PropertyLocal.java
- src/main/java/org/mae/twg/backend/models/travel/localization/ResortLocal.java
- src/main/java/org/mae/twg/backend/models/travel/localization/SightLocal.java
- src/main/java/org/mae/twg/backend/services/auth/AuthService.java
> Profile for User

- src/main/java/org/mae/twg/backend/config/SecurityConfig.java
- src/main/java/org/mae/twg/backend/controllers/ExampleController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/SightController.java
- src/main/java/org/mae/twg/backend/services/ImageService.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
Add media for headers to hotel and sight
> Refactor medai

- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/SightController.java
- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/dto/auth/UserLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/request/CommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/HotelDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/ResortDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/SightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/TourDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/HotelCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/SightCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/TourCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/CountryLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/HotelLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/PropertyLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/ResortLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/SightLightDTO.java
- src/main/java/org/mae/twg/backend/exceptions/AccessDeniedException.java
- src/main/java/org/mae/twg/backend/exceptions/CustomExceptionHandler.java
- src/main/java/org/mae/twg/backend/models/travel/comments/HotelComment.java
- src/main/java/org/mae/twg/backend/models/travel/comments/SightComment.java
- src/main/java/org/mae/twg/backend/models/travel/comments/TourComment.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/HotelCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/SightCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/TourCommentsRepo.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Добавлен интерфейс для работы с комментариями к турам, точкам интереса и отелям.
Добавлен механизм вычисления средней оценки
> Comments feature

- src/main/java/org/mae/twg/backend/dto/GradeData.java
- src/main/java/org/mae/twg/backend/dto/travel/response/HotelDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/SightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/TourDTO.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/HotelCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/SightCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/TourCommentsRepo.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Число запросов к базе для подсчета оценки на любое число записей уменьшено до одного
> Optimize grade calculation

- src/main/java/org/mae/twg/backend/controllers/auth/AuthController.java
- src/main/java/org/mae/twg/backend/models/auth/User.java
- src/main/java/org/mae/twg/backend/services/auth/AuthService.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
Так же добавлены поля даты создания и времени последнего входа
> Add logout endpoint

- src/main/java/org/mae/twg/backend/controllers/auth/ProfileController.java
- src/main/java/org/mae/twg/backend/dto/auth/SignUpRequest.java
- src/main/java/org/mae/twg/backend/dto/auth/UserDTO.java
- src/main/java/org/mae/twg/backend/models/auth/User.java
- src/main/java/org/mae/twg/backend/services/ModelType.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
> Profile image

- src/main/java/org/mae/twg/backend/controllers/ProfileController.java
- src/main/java/org/mae/twg/backend/controllers/config/ConfigBusinessController.java
- src/main/java/org/mae/twg/backend/controllers/config/ConfigVisualController.java
- src/main/java/org/mae/twg/backend/dto/auth/SignUpRequest.java
- src/main/java/org/mae/twg/backend/dto/profile/FavouriteTourDTO.java
- src/main/java/org/mae/twg/backend/dto/profile/UserDTO.java
- src/main/java/org/mae/twg/backend/dto/profile/UserLightDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/HotelCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/SightCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/TourCommentDTO.java
- src/main/java/org/mae/twg/backend/models/auth/User.java
- src/main/java/org/mae/twg/backend/services/auth/AuthService.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
- src/main/java/org/mae/twg/backend/utils/auth/JwtUtils.java
Добавлена функция добавления туров в избранное
> Add favourite tours list

- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/SightController.java
- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/models/travel/comments/HotelComment.java
- src/main/java/org/mae/twg/backend/models/travel/comments/SightComment.java
- src/main/java/org/mae/twg/backend/models/travel/comments/TourComment.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/HotelCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/SightCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/TourCommentsRepo.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Теперь пользователь может иметь только один комментарий к одной сущности
> Update comment owning policy

- src/main/java/org/mae/twg/backend/repositories/business/UserRepo.java
- src/main/java/org/mae/twg/backend/services/ImageService.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
> Add input validation

- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/repositories/travel/TourRepo.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Добавлен запрос на получение туров с участка карты
> geo-filtration

- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/repositories/travel/TourRepo.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Реализована фильтрация по различным полям
> Add filtering by title and filters

- src/main/java/org/mae/twg/backend/controllers/travel/HospitalController.java
- src/main/java/org/mae/twg/backend/dto/travel/request/geo/HospitalGeoDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/request/locals/HospitalLocalDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/HospitalDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/TourDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/comments/HospitalCommentDTO.java
- src/main/java/org/mae/twg/backend/dto/travel/response/lightDTOs/HospitalLightDTO.java
- src/main/java/org/mae/twg/backend/models/travel/Hospital.java
- src/main/java/org/mae/twg/backend/models/travel/Tour.java
- src/main/java/org/mae/twg/backend/models/travel/comments/HospitalComment.java
- src/main/java/org/mae/twg/backend/models/travel/localization/HospitalLocal.java
- src/main/java/org/mae/twg/backend/models/travel/media/HospitalMedia.java
- src/main/java/org/mae/twg/backend/repositories/travel/HospitalRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/comments/HospitalCommentsRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/images/HospitalMediaRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/localization/HospitalLocalRepo.java
- src/main/java/org/mae/twg/backend/services/travel/HospitalService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Больницы из точек интереса вынесены в отдельную таблицу
Поле больници в туре теперь указывает на новую таблицу
> Replace sight type of hospital field to hospital type

- src/main/java/org/mae/twg/backend/config/SecurityConfig.java
- src/main/java/org/mae/twg/backend/controllers/ProfileController.java
- src/main/java/org/mae/twg/backend/dto/profile/TelegramDataDTO.java
- src/main/java/org/mae/twg/backend/dto/profile/UserDTO.java
- src/main/java/org/mae/twg/backend/repositories/business/UserRepo.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
- src/main/java/org/mae/twg/backend/services/business/TourRequestService.java
- src/main/java/org/mae/twg/backend/utils/BotUtils.java
- src/main/resources/application.properties
Добавлена интеграция с ботом
- Получение id телеграм пользователя
- Рассылка о новой заявке на тур админам
> Add bot integration

- src/main/java/org/mae/twg/backend/controllers/ProfileController.java
- src/main/java/org/mae/twg/backend/controllers/auth/AuthController.java
- src/main/java/org/mae/twg/backend/controllers/business/TourRequestController.java
- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/dto/auth/UserDeleteDTO.java
- src/main/java/org/mae/twg/backend/dto/business/TourReqResponseDTO.java
- src/main/java/org/mae/twg/backend/dto/profile/ProfileDTO.java
- src/main/java/org/mae/twg/backend/repositories/business/TourRequestRepo.java
- src/main/java/org/mae/twg/backend/services/auth/AuthService.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
- src/main/java/org/mae/twg/backend/services/business/TourRequestService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
Добавлены:
- Обновление профиля по имени пользователя
- Получение списка оформленных туров для пользователя
- Создание агента и админа, а также удаление пользователя
- Получение коментария пользователоя к туру
> Update profile, auth and comments

- src/main/java/org/mae/twg/backend/controllers/travel/CountryController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/ResortController.java
- src/main/java/org/mae/twg/backend/repositories/travel/CountryRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/HotelRepo.java
- src/main/java/org/mae/twg/backend/repositories/travel/ResortRepo.java
- src/main/java/org/mae/twg/backend/services/travel/CountryService.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/ResortService.java
Добавлены необходимые фильтры для отелей, стран и курортов
> Add some filters

- src/main/java/org/mae/twg/backend/controllers/BaseController.java
- src/main/java/org/mae/twg/backend/controllers/admin/ImportExportController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HospitalController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/SightController.java
- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/resources/log4j2.xml
> Refactoring api

- src/main/java/org/mae/twg/backend/controllers/BaseController.java
- src/main/java/org/mae/twg/backend/controllers/Controller.java
- src/main/java/org/mae/twg/backend/controllers/business/TourRequestController.java
- src/main/java/org/mae/twg/backend/controllers/travel/CountryController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HospitalController.java
- src/main/java/org/mae/twg/backend/controllers/travel/HotelController.java
- src/main/java/org/mae/twg/backend/controllers/travel/ResortController.java
- src/main/java/org/mae/twg/backend/controllers/travel/SightController.java
- src/main/java/org/mae/twg/backend/controllers/travel/TourController.java
- src/main/java/org/mae/twg/backend/dto/PageDTO.java
- src/main/java/org/mae/twg/backend/dto/profile/TelegramDataDTO.java
- src/main/java/org/mae/twg/backend/models/auth/BotLink.java
- src/main/java/org/mae/twg/backend/repositories/auth/BotLinkRepo.java
- src/main/java/org/mae/twg/backend/repositories/business/TourRequestRepo.java
- src/main/java/org/mae/twg/backend/services/TravelService.java
- src/main/java/org/mae/twg/backend/services/auth/UserService.java
- src/main/java/org/mae/twg/backend/services/business/AgencyService.java
- src/main/java/org/mae/twg/backend/services/business/TourRequestService.java
- src/main/java/org/mae/twg/backend/services/news/NewsService.java
- src/main/java/org/mae/twg/backend/services/travel/CountryService.java
- src/main/java/org/mae/twg/backend/services/travel/HospitalService.java
- src/main/java/org/mae/twg/backend/services/travel/HotelService.java
- src/main/java/org/mae/twg/backend/services/travel/PropertyService.java
- src/main/java/org/mae/twg/backend/services/travel/ResortService.java
- src/main/java/org/mae/twg/backend/services/travel/SightService.java
- src/main/java/org/mae/twg/backend/services/travel/SightTypeService.java
- src/main/java/org/mae/twg/backend/services/travel/TagService.java
- src/main/java/org/mae/twg/backend/services/travel/TourService.java
- src/main/java/org/mae/twg/backend/utils/BotUtils.java
> Pagination update
